### ISSUE TITLE
cockatoo ascii art

### ISSUE THREAD

**Issue by tromp** [HarryR/cockatoo#2]
dear Harry,

Is this wonderful ascii art

        )/_                                                       
       <' \
       /)  )
    ---/'-""---                                               

your design? If so, do you mind if I use it as illustration in my Cuckoo Cycle project
https://github.com/tromp/cuckoo/tree ?
How would you like it to be attributed?
Thanks!

 -John

**Comment by HarryR** [comment]
Hi,

 No it's not my art, I found it on the internet: http://ascii.co.uk/art/cockatoo

 It's attributed as 'AsH', but I have no idea who that is.

**Comment by tromp** [comment]
Ok; I'll just mention that origin somewhere. Thanks, Harry!
